---

- name: Include initial OS-specific tasks
  include: "init_{{ ansible_os_family | lower}}.yml"
  vars:
    cvmfs_role: client

- name: Include key setup tasks
  include: keys.yml

- name: Check CernVM-FS for setup
  command: cvmfs_config chksetup
  changed_when: no
  ignore_errors: yes
  register: cvmfs_config_chksetup_out

- name: Ensure AutoFS is enabled + running
  service:
    name: autofs
    enabled: yes
    state: started

- name: Perform AutoFS and FUSE configuration for CernVM-FS
  command: cvmfs_config setup
  notify:
    - reload autofs
  args:
    creates: /etc/auto.master.d/cvmfs.autofs

- name: Configure CernVM-FS domain
  copy:
    content: |
      CVMFS_SERVER_URL="{{ item.urls | join(';') }}"
      CVMFS_KEYS_DIR=/etc/cvmfs/keys/{{ item.domain }}
    dest: /etc/cvmfs/domain.d/{{ item.domain }}.conf
    owner: root
    group: root
    mode: 0644
  with_items: "{{ cvmfs_server_urls }}"

- name: Configure CernVM-FS client settings
  copy:
    content: |
      CVMFS_REPOSITORIES="{%- for repo in cvmfs_repositories -%}{{ ',' if loop.index0 > 0 else '' }}{{ repo.repository }}{%- endfor -%}"
      CVMFS_HTTP_PROXY="{{ cvmfs_http_proxies | join(';') }}"
      CVMFS_QUOTA_LIMIT="{{ cvmfs_quota_limit | default('4000') }}"
    dest: "/etc/cvmfs/default.local"
    owner: root
    group: root
    mode: 0644

- name: Install cvmfs_wipecache setuid binary
  copy:
    src: cvmfs_wipecache.{{ ansible_distribution | lower }}_{{ ansible_distribution_major_version }}
    dest: /usr/local/bin/cvmfs_wipecache
    owner: root
    group: root
    mode: 06755
  when: cvmfs_install_setuid_cvmfs_wipecache

- name: Remove cvmfs_wipecache setuid binary
  file:
    path: /usr/local/bin/cvmfs_wipecache
    state: absent
  when: not cvmfs_install_setuid_cvmfs_wipecache

- name: Install cvmfs_remount_sync setuid binary
  copy:
    src: cvmfs_remount_sync.{{ ansible_distribution | lower }}_{{ ansible_distribution_major_version }}
    dest: /usr/local/bin/cvmfs_remount_sync
    owner: root
    group: root
    mode: 06755
  when: cvmfs_install_setuid_cvmfs_remount_sync

- name: Remove cvmfs_remount_sync setuid binary
  file:
    path: /usr/local/bin/cvmfs_remount_sync
    state: absent
  when: not cvmfs_install_setuid_cvmfs_remount_sync
