---

- name: Install apt dependencies
  apt:
    name: "{{ item }}"
  with_items:
    - apt-transport-https
    - ca-certificates

- name: Install CernVM apt key
  apt_key:
    url: https://cvmrepo.web.cern.ch/cvmrepo/apt/cernvm.gpg

- name: Configure CernVM apt repository
  apt_repository:
    filename: "cernvm.list"
    mode: 422
    repo: "deb https://cvmrepo.web.cern.ch/cvmrepo/apt/ {{ ansible_distribution_release }}-prod main"

- name: Install CernVM-FS packages and dependencies (apt)
  apt:
    name: "{{ item }}"
    state: "{{ 'latest' if _cvmfs_upgrade else 'present' }}"
  with_items: "{{ cvmfs_packages[_cvmfs_role] }}"
