---

- name: Install apt dependencies
  apt:
    name: "{{ item }}"
  with_items:
    - apt-transport-https
    - ca-certificates

- name: Install CernVM apt key
  apt_key:
    url: https://cvmrepo.web.cern.ch/cvmrepo/apt/cernvm.gpg

- name: Configure CernVM apt repository
  apt_repository:
    filename: "cernvm.list"
    mode: 422
    repo: "deb [allow-insecure=true] https://cvmrepo.web.cern.ch/cvmrepo/apt/ {{ ansible_distribution_release }}-prod main"
  when: ansible_distribution != 'Ubuntu'

- name: Configure CernVM apt repository
  apt_repository:
    filename: "cernvm.list"
    mode: 422
    repo: "deb [allow-insecure=true] https://cvmrepo.web.cern.ch/cvmrepo/apt/ {{ ansible_distribution_release }}-prod main"
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release in ('xenial', 'precise')

  # There are no packages for bionic. Or any of the non LTS versions so good
  # luck and have fun if that's you.
- name: Configure CernVM apt repository
  apt_repository:
    filename: "cernvm.list"
    mode: 422
    repo: "deb [allow-insecure=true] https://cvmrepo.web.cern.ch/cvmrepo/apt/ xenial-prod main"
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release not in ('xenial', 'precise')

- name: Install CernVM-FS packages and dependencies (apt)
  apt:
    name: "{{ item }}"
    state: "{{ 'latest' if _cvmfs_upgrade else 'present' }}"
  with_items: "{{ cvmfs_packages[_cvmfs_role] }}"
