---
# tasks file for galaxyproject.cvmfs

- name: Prepare yum for CernVM installation
  include: repo_redhat.yml
  when: ansible_os_family == "RedHat"

- name: Prepare apt for CernVM installation
  include: repo_debian.yml
  when: ansible_os_family == "Debian"

- include: client.yml
  when: "'cvmfsclients' in group_names or cvmfs_role == 'client'"

- include: stratum1.yml
  when: "'cvmfsstratum1servers' in group_names or cvmfs_role == 'stratum1'"

- include: stratum0.yml
  when: "'cvmfsstratum0servers' in group_names or cvmfs_role == 'stratum0'"

- include: localproxy.yml
  when: "'cvmfslocalproxies' in group_names or cvmfs_role == 'localproxy'"
