---
# tasks file for galaxyproject.cvmfs

- name: Set OS-specific variables
  include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Set facts for Galaxy CVMFS repositories, if enabled
  set_fact:
    cvmfs_keys: "{{ cvmfs_keys }} + {{ galaxy_cvmfs_keys }}"
    cvmfs_server_urls: "{{ cvmfs_server_urls }} + {{ galaxy_cvmfs_server_urls }}"
    cvmfs_repositories: "{{ cvmfs_repositories }} + {{ galaxy_cvmfs_repositories }}"
    cvmfs_config_apache_flag: "{{ '-p' if not cvmfs_config_apache else '' }}"
  when: galaxy_cvmfs_repos_enabled

- include_tasks: client.yml
  when: "'cvmfsclients' in group_names or cvmfs_role == 'client'"

- include_tasks: stratum1.yml
  when: "'cvmfsstratum1servers' in group_names or cvmfs_role == 'stratum1'"

- include_tasks: stratum0.yml
  when: "'cvmfsstratum0servers' in group_names or cvmfs_role == 'stratum0'"

- include_tasks: localproxy.yml
  when: "'cvmfslocalproxies' in group_names or cvmfs_role == 'localproxy'"
