---

# TODO: `systemctl unmask tmp.mount` to make /tmp tmpfs (`cvmfs_server import`
# fails if /tmp is xfs, although for some reason was fine on the PSU stratum 0
# w/ xfs /tmp).

- name: Include initial OS-specific tasks
  include: "init_{{ ansible_os_family | lower }}.yml"
  vars:
    _cvmfs_role: stratum0

- name: Include key setup tasks
  include: keys.yml

- name: Install CernVM-FS private keys
  copy:
    content: "{{ item.key }}"
    dest: "{{ item.path }}"
    owner: "{{ item.owner | default('root') }}"
    group: "root"
    mode: "0400"
  with_items: "{{ cvmfs_private_keys }}"

- name: Include stratumN tasks
  include: stratumN.yml

- name: Include Apache tasks
  include: apache.yml

- name: Include firewall tasks
  include: firewall.yml
  vars:
    _cvmfs_http_ports: "{{ cvmfs_stratum0_http_ports }}"
  when: cvmfs_manage_firewall

- name: Create repositories
  command: /usr/bin/cvmfs_server mkfs {{ cvmfs_config_apache_flag }} -o {{ item.owner | default('root') }} -f {{ cvmfs_union_fs }} {{ item.repository }}
  args:
    creates: /srv/cvmfs/{{ item.repository }}
  with_items: "{{ cvmfs_repositories }}"
  notify:
    - restart apache

- name: Ensure repositories are imported
  command: /usr/bin/cvmfs_server import -r {{ cvmfs_config_apache_flag }} -o {{ item.owner | default('root') }} -f overlayfs {{ item.repository }}
  args:
    creates: /etc/cvmfs/repositories.d/{{ item.repository }}
  with_items: "{{ cvmfs_repositories }}"
  notify:
    - restart apache

- name: Include repository server options tasks
  include: options.yml
  vars:
    _cvmfs_repo_option_key: server

- name: Include repository server options tasks
  include: options.yml
  vars:
    _cvmfs_repo_option_key: client

- name: Increase default max file descriptor limit
  lineinfile:
    dest: "/etc/security/limits.conf"
    regexp: '^\*\s+{{ item }}\s+nofile\s+\d+$'
    line: "*               {{ item }}    nofile          {{ cvmfs_numfiles }}"
  with_items:
    - soft
    - hard
  when: cvmfs_numfiles is defined

- name: Schedule key resignings
  cron:
    name: "Re-sign CVMFS keys"
    cron_file: "ansible_cvmfs_key_resign"
    user: "root"
    hour: 11
    minute: 0
    weekday: 2
    job: "/usr/bin/cvmfs_server resign {{ cvmfs_repositories | join(' ; /usr/bin/cvmfs_server resign ', attribute='repository' ) }}"

- name: Include garbage collection tasks
  include: gc.yml
